// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJqaaDjTzGR6DA2N_XTYIom4wsaI-OQ9A',
    appId: '1:604285657147:web:7aea43d0b159b2d8e0fc1e',
    messagingSenderId: '604285657147',
    projectId: 'mindquest-8c1dc',
    authDomain: 'mindquest-8c1dc.firebaseapp.com',
    storageBucket: 'mindquest-8c1dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Qv9N0lRwDxdY3WPVVTEFQDi3Qu77HoY',
    appId: '1:604285657147:android:1424a90efe01abcee0fc1e',
    messagingSenderId: '604285657147',
    projectId: 'mindquest-8c1dc',
    storageBucket: 'mindquest-8c1dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODjvHSRt6cuzVBkjZQFGhnFkuU2-JR1c',
    appId: '1:604285657147:ios:9a5ada0878a07c81e0fc1e',
    messagingSenderId: '604285657147',
    projectId: 'mindquest-8c1dc',
    storageBucket: 'mindquest-8c1dc.firebasestorage.app',
    iosBundleId: 'com.example.quizApplicationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODjvHSRt6cuzVBkjZQFGhnFkuU2-JR1c',
    appId: '1:604285657147:ios:9a5ada0878a07c81e0fc1e',
    messagingSenderId: '604285657147',
    projectId: 'mindquest-8c1dc',
    storageBucket: 'mindquest-8c1dc.firebasestorage.app',
    iosBundleId: 'com.example.quizApplicationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJqaaDjTzGR6DA2N_XTYIom4wsaI-OQ9A',
    appId: '1:604285657147:web:1a5ffc5db6468f40e0fc1e',
    messagingSenderId: '604285657147',
    projectId: 'mindquest-8c1dc',
    authDomain: 'mindquest-8c1dc.firebaseapp.com',
    storageBucket: 'mindquest-8c1dc.firebasestorage.app',
  );
}
